### ISSUE TITLE
comment pourrait-on faire pour qu'un squelette récupère des données distantes ?

### ISSUE THREAD

**Issue by herveheritier** [SkodgeeTeam/skodgee#5]
Sujet de réflexion ouvert par cette question qui peut cacher beaucoup de chose !
Supposons que pour générer un document il soit nécessaire d'aller chercher des données distantes ; on peut imaginer que des directives prennent cela en charge...

**Comment by SkodgeeTeam** [comment]
La  [branche remoteExperiment](https://github.com/SkodgeeTeam/skodgee/tree/remoteExperiment) a été ouverte pour creuser le sujet.
